export const slideItems = [
  {
    id: 1,
    img: 'thank_for_shopping.jpg',
    title: 'Summer Sale',
    desc: "Don't compromise on style! Get flat 30% off for new arrivals.",
    bg: 'f5fafd',
  },
  {
    id: 2,
    img: 'thank_for_shopping.jpg',
    title: 'Winter Sale',
    desc: "Don't compromise on style! Get flat 30% off for new arrivals.",
    bg: 'fcf1ed',
  },
  {
    id: 3,
    img: 'thank_for_shopping.jpg',
    title: 'Popular Sale',
    desc: "Don't compromise on style! Get flat 30% off for new arrivals.",
    bg: 'fbf0f4',
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
    cat: "women",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
    cat: "coat",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
    cat: "jeans",
  },
];

export const productsFromServer = [
  {
    id:1,
    img:"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    name: 't-shirt',
    color: 'white',
    size: 'xs',
    sort: 'newest',
    price: 20,
  },
  {
    id:2,
    img:"https://cdn.shopify.com/s/files/1/0101/4832/products/Angela_Natural_Tee.png?v=1606780388",
    name: 't-shirt',
    color: 'white',
    size: 's',
    sort: 'asc',
    price: 30,
  },
  {
    id:3,
    img:"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    name: 't-shirt',
    color: 'black',
    size: 'm',
    sort: 'newest',
    price: 40,
  },
  {
    id:4,
    img:"https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    name: 'dress',
    color: 'red',
    size: 'l',
    sort: 'asc',
    price: 50,
  },
  {
    id:5,
    img:"https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    name: 'bag',
    color: 'blue',
    size: 'xl',
    sort: 'desc',
    price: 60,
  },
  {
    id:6,
    img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    name: 'cap',
    color: 'yellow',
    size: 'xxl',
    sort: 'newest',
    price: 70,
  },
  {
    id:7,
    // img:"Black-Jacket-Transparent-Image.png",
    img:"http://localhost:3000/Black-Jacket-Transparent-Image.png",
    name: 'jacket',
    color: 'green',
    size: 'm',
    sort: 'asc',
    price: 80,
  },
  {
    id:8,
    img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    name: 'coat',
    color: 'blue',
    size: 'l',
    sort: 'desc',
    price: 90,
  },
];
